<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import { useApi } from '../composables/useApi'
import type { StatsResponse } from '../types'

type Severity = 'stable' | 'watch' | 'urgent'
interface Recommendation { severity: Severity; title: string; body: string; evidence: string; action: string }

const api = useApi()
const rawMetrics = ref('')
const stats = ref<StatsResponse | null>(null)
const ingestBuffer = ref<{ pending_bytes: number; pending_count: number; max_bytes: number; used_pct: number; oldest_age_secs: number } | null>(null)
const loading = ref(false)
const error = ref('')
const refreshedAt = ref<Date | null>(null)
let refreshTimer: ReturnType<typeof setInterval> | undefined

function parseMetrics(text: string): Map<string, number> {
  const values = new Map<string, number>()
  for (const line of text.split('\n')) {
    if (!line || line.startsWith('#')) continue
    const match = line.match(/^([a-zA-Z_:][a-zA-Z0-9_:]*)(?:\{[^}]*\})?\s+([-+0-9.eEInfNa]+)$/)
    if (!match) continue
    const name = match[1]
    const sample = match[2]
    if (!name || sample === undefined) continue
    const value = Number(sample)
    if (!Number.isFinite(value)) continue
    // Labelled samples are summed for capacity totals. All metric labels are
    // fixed low-cardinality labels generated by the services.
    values.set(name, (values.get(name) || 0) + value)
  }
  return values
}

const metrics = computed(() => parseMetrics(rawMetrics.value))
function metric(name: string): number { return metrics.value.get(name) || 0 }

async function load() {
  loading.value = true
  error.value = ''
  try {
    const now = new Date()
    const [metricText, currentStats, buffer] = await Promise.all([
      api.getSystemMetrics(),
      api.getStats({ time_range: { from: new Date(now.getTime() - 3600000).toISOString(), to: now.toISOString() } }),
      api.getIngestBuffer(),
    ])
    rawMetrics.value = metricText
    stats.value = currentStats
    ingestBuffer.value = buffer
    refreshedAt.value = new Date()
  } catch (e: any) {
    error.value = e?.message || 'Unable to load capacity telemetry.'
  } finally {
    loading.value = false
  }
}

onMounted(() => {
  load()
  refreshTimer = setInterval(load, 15000)
})
onUnmounted(() => { if (refreshTimer) clearInterval(refreshTimer) })

function formatBytes(bytes: number): string {
  if (bytes >= 1099511627776) return `${(bytes / 1099511627776).toFixed(2)} TiB`
  if (bytes >= 1073741824) return `${(bytes / 1073741824).toFixed(2)} GiB`
  if (bytes >= 1048576) return `${(bytes / 1048576).toFixed(1)} MiB`
  if (bytes >= 1024) return `${(bytes / 1024).toFixed(1)} KiB`
  return `${Math.round(bytes)} B`
}
function formatCount(value: number): string {
  if (value >= 1e9) return `${(value / 1e9).toFixed(1)}B`
  if (value >= 1e6) return `${(value / 1e6).toFixed(1)}M`
  if (value >= 1e3) return `${(value / 1e3).toFixed(1)}K`
  return Math.round(value).toLocaleString()
}
function formatDuration(ms: number): string {
  if (!ms) return '—'
  return ms >= 1000 ? `${(ms / 1000).toFixed(1)}s` : `${Math.round(ms)}ms`
}
function highestSeverity(items: Recommendation[]): Severity {
  if (items.some(item => item.severity === 'urgent')) return 'urgent'
  if (items.some(item => item.severity === 'watch')) return 'watch'
  return 'stable'
}

const storageBytes = computed(() => stats.value?.storage.reduce((sum, table) => sum + table.bytes_on_disk, 0) || 0)
const storageRows = computed(() => stats.value?.storage.reduce((sum, table) => sum + table.total_rows, 0) || 0)
const diskFree = computed(() => metric('rush_stats_disk_local_free_bytes'))
const diskTotal = computed(() => metric('rush_stats_disk_local_total_bytes'))
const diskUsedPct = computed(() => diskTotal.value > 0 ? ((diskTotal.value - diskFree.value) / diskTotal.value) * 100 : 0)
const processMemory = computed(() => metric('rush_process_resident_memory_bytes'))
const chMemory = computed(() => Math.max(metric('rush_ch_memory_tracking_bytes'), metric('rush_ch_memory_resident_bytes')))
const queryP95 = computed(() => metric('rush_ch_query_log_p95_duration_ms'))
const activeQueries = computed(() => metric('rush_ch_active_queries'))
const activeMerges = computed(() => metric('rush_ch_active_merges'))
const activeMutations = computed(() => metric('rush_ch_active_mutations'))
const maxParts = computed(() => metric('rush_ch_max_part_count_for_partition'))
const spoolPct = computed(() => ingestBuffer.value?.used_pct || metric('rush_ingest_spool_bytes') / Math.max(1, ingestBuffer.value?.max_bytes || 1) * 100)

const recommendations = computed<Recommendation[]>(() => {
  const items: Recommendation[] = []
  if (spoolPct.value >= 70 || (ingestBuffer.value?.oldest_age_secs || 0) >= 300) {
    items.push({ severity: 'urgent', title: 'Ingest is falling behind', body: 'The durable buffer is retaining data instead of writing cleanly to ClickHouse.', evidence: `${spoolPct.value.toFixed(1)}% spool utilization · oldest ${Math.round(ingestBuffer.value?.oldest_age_secs || 0)}s`, action: 'Add ClickHouse write capacity or storage first. Adding API pods will not clear a saturated database.' })
  }
  if (queryP95.value >= 5000 || activeQueries.value >= 16) {
    items.push({ severity: 'urgent', title: 'Read pressure is high', body: 'Interactive queries are competing for database resources.', evidence: `p95 ${formatDuration(queryP95.value)} · ${formatCount(activeQueries.value)} active queries`, action: 'Add query-api pods for request concurrency, then add ClickHouse read capacity or shards if the database remains saturated.' })
  } else if (queryP95.value >= 1500 || activeQueries.value >= 8) {
    items.push({ severity: 'watch', title: 'Query headroom is narrowing', body: 'The current workload is still serving, but latency or concurrency is approaching the scale-out guide.', evidence: `p95 ${formatDuration(queryP95.value)} · ${formatCount(activeQueries.value)} active queries`, action: 'Profile the slowest query families. Plan another query-api pod or ClickHouse read capacity if this persists.' })
  }
  if (diskUsedPct.value >= 85) {
    items.push({ severity: 'urgent', title: 'Local ClickHouse disk is nearly full', body: 'Disk pressure can block merges and eventually stop ingestion.', evidence: `${diskUsedPct.value.toFixed(1)}% local disk used`, action: 'Add disk capacity or move more data to object storage; sharding is appropriate when one node cannot hold the retention footprint.' })
  } else if (diskUsedPct.value >= 70) {
    items.push({ severity: 'watch', title: 'Local disk needs a plan', body: 'Storage is entering the range where retention, merges, and ingest bursts can collide.', evidence: `${diskUsedPct.value.toFixed(1)}% local disk used`, action: 'Review retention and tiering. Add disk or a shard before crossing 85%.' })
  }
  if (maxParts.value >= 1000 || activeMerges.value >= 8 || activeMutations.value >= 5) {
    items.push({ severity: 'watch', title: 'Merge pressure is elevated', body: 'Parts or background work are accumulating faster than ClickHouse is consolidating them.', evidence: `${Math.round(maxParts.value)} max parts · ${Math.round(activeMerges.value)} merges · ${Math.round(activeMutations.value)} mutations`, action: 'Reduce tiny inserts, increase merge resources, or shard write volume before adding more query-api pods.' })
  }
  if (chMemory.value >= 8 * 1024 ** 3 || processMemory.value >= 4 * 1024 ** 3) {
    items.push({ severity: 'watch', title: 'Memory is a scaling signal', body: 'The observed process or ClickHouse resident memory is high enough to make eviction and OOM risk material.', evidence: `API ${formatBytes(processMemory.value)} · ClickHouse ${formatBytes(chMemory.value)}`, action: 'Set explicit memory limits and inspect the largest query families. Add memory or shard heavy workloads when the limit is consistently approached.' })
  }
  return items.length ? items : [{ severity: 'stable', title: 'No immediate scale action', body: 'The measured signals are below the operating thresholds shown below.', evidence: `storage ${formatBytes(storageBytes.value)} · ${formatCount(storageRows.value)} rows`, action: 'Keep collecting a baseline. Scale before a threshold is crossed, not after requests start failing.' }]
})

const systemSeverity = computed(() => highestSeverity(recommendations.value))
const statusLabel = computed(() => systemSeverity.value === 'urgent' ? 'Action required' : systemSeverity.value === 'watch' ? 'Watch closely' : 'Within guide')

const guideRows = [
  { signal: 'Spool utilization / age', threshold: '70% or 5m oldest age', move: 'ClickHouse write capacity; then API pods' },
  { signal: 'Query p95 / active queries', threshold: '1.5s / 8 watch · 5s / 16 urgent', move: 'API pods for concurrency; CH read capacity for saturation' },
  { signal: 'Local disk', threshold: '70% watch · 85% urgent', move: 'Tier, add disk, or shard retention footprint' },
  { signal: 'Parts / merges', threshold: '1,000 parts · 8 merges', move: 'Fewer tiny inserts, more merge resources, or shard writes' },
  { signal: 'Observed memory', threshold: '8 GiB CH · 4 GiB API guide', move: 'Set limits, add memory, or shard heavy workloads' },
]
</script>

<template>
  <div class="capacity-page">
    <header class="capacity-header">
      <div><div class="capacity-kicker">Control / capacity</div><h1>System state</h1><p>One place to decide whether the next move is more pods, more memory, more disk, or another ClickHouse shard.</p></div>
      <div class="capacity-actions"><span v-if="refreshedAt" class="capacity-updated mono">updated {{ refreshedAt.toLocaleTimeString() }}</span><button class="capacity-refresh" type="button" :disabled="loading" @click="load">{{ loading ? 'Refreshing…' : 'Refresh' }}</button></div>
    </header>

    <div v-if="error" class="capacity-error">{{ error }} <button type="button" @click="load">Retry</button></div>

    <section class="posture-banner" :class="`posture-${systemSeverity}`">
      <div class="posture-mark" aria-hidden="true"><span></span></div>
      <div class="posture-copy"><div class="posture-label">Current capacity posture</div><strong>{{ statusLabel }}</strong><p>{{ systemSeverity === 'urgent' ? 'A resource boundary is being approached now.' : systemSeverity === 'watch' ? 'The system is serving, but one or more signals are narrowing headroom.' : 'No measured signal currently calls for an immediate scale change.' }}</p></div>
      <div class="posture-refresh mono">polling every 15s</div>
    </section>

    <div class="capacity-grid">
      <section class="capacity-card capacity-card--wide"><div class="card-kicker">Read path</div><h2>Query pressure</h2><div class="capacity-stat-grid"><div><span>Recent p95</span><strong>{{ formatDuration(queryP95) }}</strong><small>ClickHouse query log · 5m</small></div><div><span>Active queries</span><strong>{{ formatCount(activeQueries) }}</strong><small>currently executing</small></div><div><span>Longest query</span><strong>{{ formatDuration(metric('rush_ch_longest_running_query_secs') * 1000) }}</strong><small>current process list</small></div><div><span>Recent errors</span><strong>{{ formatCount(metric('rush_ch_query_log_recent_errors')) }}</strong><small>query log · 5m</small></div></div></section>
      <section class="capacity-card"><div class="card-kicker">Write path</div><h2>Ingest pressure</h2><div class="capacity-primary"><strong>{{ spoolPct.toFixed(1) }}%</strong><span>spool used</span></div><div class="meter"><span :class="{ danger: spoolPct >= 70 }" :style="{ width: `${Math.min(100, spoolPct)}%` }"></span></div><dl class="compact-facts"><div><dt>Pending</dt><dd>{{ formatBytes(ingestBuffer?.pending_bytes || 0) }}</dd></div><div><dt>Oldest</dt><dd>{{ Math.round(ingestBuffer?.oldest_age_secs || 0) }}s</dd></div><div><dt>Delayed inserts</dt><dd>{{ formatCount(metric('rush_ch_delayed_inserts')) }}</dd></div></dl></section>
      <section class="capacity-card"><div class="card-kicker">Storage</div><h2>ClickHouse footprint</h2><div class="capacity-primary"><strong>{{ formatBytes(storageBytes) }}</strong><span>stored locally</span></div><div v-if="diskTotal" class="meter"><span :class="{ danger: diskUsedPct >= 85 }" :style="{ width: `${Math.min(100, diskUsedPct)}%` }"></span></div><dl class="compact-facts"><div><dt>Local disk</dt><dd>{{ diskTotal ? `${diskUsedPct.toFixed(1)}% used` : 'capacity unavailable' }}</dd></div><div><dt>Rows</dt><dd>{{ formatCount(storageRows) }}</dd></div><div><dt>Parts peak</dt><dd>{{ formatCount(maxParts) }}</dd></div></dl></section>
      <section class="capacity-card"><div class="card-kicker">Background work</div><h2>Merge pressure</h2><div class="capacity-primary"><strong>{{ formatCount(activeMerges) }}</strong><span>active merges</span></div><dl class="compact-facts"><div><dt>Mutations</dt><dd>{{ formatCount(activeMutations) }}</dd></div><div><dt>Longest merge</dt><dd>{{ formatDuration(metric('rush_ch_longest_running_merge_secs') * 1000) }}</dd></div><div><dt>Pool tasks</dt><dd>{{ formatCount(metric('rush_ch_background_pool_task')) }}</dd></div></dl></section>
      <section class="capacity-card"><div class="card-kicker">Process</div><h2>API runtime</h2><div class="capacity-primary"><strong>{{ formatBytes(processMemory) }}</strong><span>resident memory</span></div><dl class="compact-facts"><div><dt>CPU time</dt><dd>{{ metric('rush_process_cpu_seconds_total').toFixed(1) }}s</dd></div><div><dt>Open FDs</dt><dd>{{ formatCount(metric('rush_process_open_fds')) }}</dd></div><div><dt>Tokio tasks</dt><dd>{{ formatCount(metric('rush_runtime_alive_tasks')) }}</dd></div></dl></section>
    </div>

    <section class="recommendations-section"><div class="section-heading"><div><div class="capacity-kicker">Decision support</div><h2>What to do next</h2><p>These are operating heuristics, not automatic scaling actions. Look for a sustained signal across several refreshes.</p></div><span class="threshold-note">bounded guide · no tenant labels</span></div><div class="recommendation-list"><article v-for="item in recommendations" :key="item.title" class="recommendation" :class="`recommendation--${item.severity}`"><div class="recommendation-icon" aria-hidden="true"></div><div class="recommendation-body"><div class="recommendation-top"><h3>{{ item.title }}</h3><span>{{ item.severity === 'urgent' ? 'act now' : item.severity === 'watch' ? 'watch' : 'stable' }}</span></div><p>{{ item.body }}</p><div class="recommendation-evidence mono">{{ item.evidence }}</div><div class="recommendation-action"><b>Next move</b> {{ item.action }}</div></div></article></div></section>

    <section class="guide-section"><div class="section-heading"><div><div class="capacity-kicker">Runbook thresholds</div><h2>Scale signals</h2></div><span class="threshold-note">starting points for this deployment</span></div><div class="guide-table-wrap"><table class="guide-table"><thead><tr><th>Signal</th><th>Watch / urgent</th><th>Preferred response</th></tr></thead><tbody><tr v-for="row in guideRows" :key="row.signal"><td>{{ row.signal }}</td><td class="mono">{{ row.threshold }}</td><td>{{ row.move }}</td></tr></tbody></table></div></section>
  </div>
</template>

<style scoped src="../styles/views/CapacityView.css"></style>
